(function ($) {
"use strict";
$(window).on('scroll', function () { var scroll=$(window).scrollTop(); if(scroll<400){$("#sticky-header").removeClass("sticky");$('#back-top').fadeIn(500);}else{$("#sticky-header").addClass("sticky");$('#back-top').fadeIn(500);} });
$(document).ready(function(){
var menu=$('ul#navigation'); if(menu.length){menu.slicknav({prependTo:".mobile_menu",closedSymbol:'+',openedSymbol:'-'});}
// Looping duplicates carousel slides in the live DOM. Keep finite carousels to avoid repeated homepage content and headings.
$('.slider_active').owlCarousel({loop:false,rewind:true,margin:0,items:1,autoplay:true,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:false,autoplayHoverPause:true,autoplaySpeed:800,animateOut:'fadeOut',animateIn:'fadeIn',responsive:{0:{items:1,nav:false},767:{items:1,nav:false},992:{items:1,nav:true},1200:{items:1,nav:true},1600:{items:1,nav:true}}});
$('.testmonial_active').owlCarousel({loop:false,rewind:true,margin:30,items:1,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:false,autoplayHoverPause:true,autoplaySpeed:800,responsive:{0:{items:1,dots:false,nav:false},767:{items:1,dots:false,nav:false},992:{items:1,nav:false},1200:{items:1,nav:false},1500:{items:1}}});
$('.service_active').owlCarousel({loop:false,rewind:true,margin:30,items:1,autoplay:true,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:false,autoplayHoverPause:true,autoplaySpeed:800,responsive:{0:{items:1,nav:false},767:{items:2},992:{items:3,nav:false},1200:{items:3},1500:{items:3,nav:true}}});
$('.case_active').owlCarousel({loop:false,rewind:true,margin:30,items:1,autoplay:false,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:true,autoplayHoverPause:true,autoplaySpeed:800,center:false,responsive:{0:{items:1,nav:false},767:{items:3,nav:false},992:{items:3,nav:false},1200:{items:3,nav:false},1500:{items:3,nav:true}}});
$('.property_banner_active').owlCarousel({loop:false,rewind:true,margin:30,items:1,autoplay:false,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:true,autoplayHoverPause:true,autoplaySpeed:800,center:false,responsive:{0:{items:1,nav:false},767:{items:1,nav:false},992:{items:1},1200:{items:1},1500:{items:1,nav:true}}});
var $grid=$('.grid').isotope({itemSelector:'.grid-item',percentPosition:true,masonry:{columnWidth:'.grid-item'}}); $('.portfolio-menu').on('click','button',function(){var filterValue=$(this).attr('data-filter');$grid.isotope({filter:filterValue});}); $('.portfolio-menu button').on('click',function(event){$(this).siblings('.active').removeClass('active');$(this).addClass('active');event.preventDefault();});
var testimonialSliders=document.querySelectorAll('[data-testimonial-slider]'); testimonialSliders.forEach(function(slider){var slides=slider.querySelectorAll('[data-testimonial-slide]'),prevButton=slider.querySelector('[data-testimonial-prev]'),nextButton=slider.querySelector('[data-testimonial-next]'),currentIndex=0,autoSlideId;if(!slides.length)return;function showSlide(index){slides[currentIndex].classList.remove('is-active');currentIndex=(index+slides.length)%slides.length;slides[currentIndex].classList.add('is-active');}function stopAutoSlide(){window.clearInterval(autoSlideId);autoSlideId=null;}function startAutoSlide(){if(slides.length<2||autoSlideId)return;autoSlideId=window.setInterval(function(){showSlide(currentIndex+1);},5000);}function resetAutoSlide(){stopAutoSlide();startAutoSlide();}if(prevButton)prevButton.addEventListener('click',function(){showSlide(currentIndex-1);resetAutoSlide();});if(nextButton)nextButton.addEventListener('click',function(){showSlide(currentIndex+1);resetAutoSlide();});slider.addEventListener('mouseenter',stopAutoSlide);slider.addEventListener('mouseleave',startAutoSlide);slider.addEventListener('touchstart',stopAutoSlide,{passive:true});slider.addEventListener('touchend',startAutoSlide);showSlide(0);startAutoSlide();});
new WOW().init(); $('.counter').counterUp({delay:10,time:10000}); $('.popup-image').magnificPopup({type:'image',gallery:{enabled:true}});$('.img-pop-up').magnificPopup({type:'image',gallery:{enabled:true}});$('.popup-video').magnificPopup({type:'iframe'}); $.scrollIt({upKey:38,downKey:40,easing:'linear',scrollTime:600,activeClass:'active',onPageChange:null,topOffset:0}); $.scrollUp({scrollName:'scrollUp',topDistance:'4500',topSpeed:300,animation:'fade',animationInSpeed:200,animationOutSpeed:200,scrollText:'<i class="fa fa-angle-double-up"></i>',activeOverlay:false});
$('.brand-active').owlCarousel({loop:false,rewind:true,margin:30,items:1,autoplay:true,nav:false,dots:false,autoplayHoverPause:true,autoplaySpeed:800,responsive:{0:{items:1,nav:false},767:{items:4},992:{items:7}}}); $('.project-active').owlCarousel({loop:false,rewind:true,margin:30,items:1,navText:['<i class="Flaticon flaticon-left-arrow"></i>','<i class="Flaticon flaticon-right-arrow"></i>'],nav:true,dots:false,responsive:{0:{items:1,nav:false},767:{items:1,nav:false},992:{items:2,nav:false},1200:{items:1},1501:{items:2}}}); if(document.getElementById('default-select')){$('select').niceSelect();} $('.details_active').owlCarousel({loop:false,rewind:true,margin:0,items:1,navText:['<i class="ti-angle-left"></i>','<i class="ti-angle-right"></i>'],nav:true,dots:false,responsive:{0:{items:1,nav:false},767:{items:1,nav:false},992:{items:1,nav:false},1200:{items:1}}});
});
$(document).ready(function(){$('.popup-with-form').magnificPopup({type:'inline',preloader:false,focus:'#name',callbacks:{beforeOpen:function(){if($(window).width()<700){this.st.focus=false;}else{this.st.focus='#name';}}}});});
function mailChimp(){$('#mc_embed_signup').find('form').ajaxChimp();} mailChimp(); $("#search_input_box").hide();$("#search").on("click",function(){$("#search_input_box").slideToggle();$("#search_input").focus();});$("#close_search").on("click",function(){$('#search_input_box').slideUp(500);});$("#search_input_box").hide();$("#search_1").on("click",function(){$("#search_input_box").slideToggle();$("#search_input").focus();});$(document).ready(function(){$('select').niceSelect();});
})(jQuery);